### PR TITLE
Ignore this...

### PR DESCRIPTION
**Pull request by catalincraciun**
I have targeted your master instead of my fork's master. Really sorry

### CODE REVIEW

**Comment by Murkantilism** [comment]
Hi, no worries! Wow, this looks like a ton of work! I'm very impressed.

Though I'm kinda sad you called the original version ugly and unplayable in your readme. Yea there were certainly bugs, but that's what happens when you're a fulltime student without the time to fix everything. And I'm sure Jen would have a thing or two to say about calling her art style ugly, I think she's a brilliant artist.

**Comment by catalincraciun** [comment]
Hello, thank you, we had a month full of work. The original version had a couple of bugs, it wasn't not ugly considering the artwork, but I would say that it wasn't playable. Will change that in the README.md. We are also full-time students. Maybe you want to check the new version at: http://catalincraciun.me/Chromacore Your feedback would be very important for us.

**Comment by Murkantilism** [comment]
I have! It's awesome, very fun to play. Some feedback I have:
- Highlight the box obstacles. One of the most common pieces of feedback/usability complaints I got was that people had trouble discerning between what was an obstacle and a prop. This is especially important for your version since you darkened everything. My solution was to through a bright red outline around the box sprite.
- One of the biggest issues when I was designing levels was to make sure that players don't fall out of sync with the music. Running into an obstacle causes each mystic ball's music section to be off by a little bit, however since you guys changed the game so the player loses when they fall too far behind perhaps desynced music is acceptable. Something to think about.
- Hard to tell that the helicopter prop is a prop and not an obstacle.

Overall I love the changes you guys made. The flickering lights, new props and level platforms, and the UI changes are fantastic! Awesome work! How did you guys do in the Game Off? I can't seem to find a winner's page for 2015.

**Comment by catalincraciun** [comment]
Thank you for your detailed feedback, we will definitely take what you have said in consideration. Game Off ends on 13 April, that's why you don't see a winner's page for this year, but we are very hopeful.

I am so glad you like it, maybe you will take into consideration at some point in the future our random and  infinite generation algorithm, I have seen it will be coming soon on Android (an automatic level builder).

**Comment by Murkantilism** [comment]
Ah that makes sense, well best of luck in the competition then! I will definitely poke through your code when I get the chance!

**Comment by catalincraciun** [comment]
Thank you! You can find the code related to that in the SceneManagement.cs. Keep in touch. Goodbye.

**Pull request closed without merging**
